//! Emit TypeScript type bindings for the wire-level Rust types.
//!
//! Invoked indirectly via `cargo xtask gen-types`. ts-rs is the source
//! of truth for the *content* of the generated types (via the `TS`
//! derive on each wire type), but we drive the file writes ourselves
//! rather than calling `T::export_all()`. ts-rs's built-in export path
//! does an atomic temp-file-plus-rename dance that fails with
//! PermissionDenied on WSL2 + Docker Desktop bind mounts; a plain
//! `std::fs::write` works fine. This shim keeps the build path
//! portable across host platforms.
//!
//! When a new endpoint lands, add its wire types here. Each
//! `exports.add::<T>()` call emits `<T-name>.ts` in the generated dir.
//! Transitive dependencies need their own line — ts-rs doesn't surface
//! them when we drive the writes ourselves.
//!
//! Those calls are the only list: collection finishes before any file
//! is written, so the `import type` lines each file needs are resolved
//! against the set that was actually exported. A forgotten type is a
//! missing file (and a compile error in the web UI that names it) —
//! never a silently missing import in a file that still looks
//! plausible.

use std::path::Path;

use ts_rs::TS;

use strum::VariantArray;
use workdown_core::git_data::{GitPullResult, GitStatus};
use workdown_core::item_data::ItemDetail;
use workdown_core::model::diagnostic::{
    CollectionDiagnostic, CollectionDiagnosticKind, ConfigDiagnostic, ConfigDiagnosticKind,
    Diagnostic, DiagnosticBody, FieldValueError, FileDiagnostic, FileDiagnosticKind,
    FilesDiagnostic, FilesDiagnosticKind, ItemDiagnostic, ItemDiagnosticKind, RangeBound,
};
use workdown_core::model::field_value::FieldValue;
use workdown_core::model::schema::{FieldType, Severity};
use workdown_core::model::view_slots;
use workdown_core::model::views::{Aggregate, Bucket, DisplayConfig, ViewSummary, ViewType};
use workdown_core::model::WorkItemId;
use workdown_core::mutation_data::{
    CreateItem, CreateItemResult, CreateView, FieldMutation, FieldMutationResult, SetViewFilter,
    UpdateView, ViewDefinition, ViewMutationResult,
};
use workdown_core::project_data::ProjectIdentity;
use workdown_core::query::clause::{Clause, Condition};
use workdown_core::query::types::Operator;
use workdown_core::schema_data::{
    FieldSchema, FieldTypeOperators, PaletteColor, ResourceList, ResourceOption, SchemaData,
};
use workdown_core::timer_data::{
    EffortFieldState, StartTimer, TimerMode, TimerPhase, TimerStartOutcome, TimerState,
    TimerStopResult, TimerWrite,
};
use workdown_core::view_data::{
    BarChartBar, BarChartData, BoardColumn, BoardData, Card, CardField, ChartValue, Column, Edge,
    GanttBar, GanttByDepthData, GanttByInitiativeData, GanttData, GraphData, HeatmapCell,
    HeatmapData, Initiative, ItemRef, Level, LineChartData, LinePoint, LineSeries, MetricData,
    MetricRowData, SizeValue, TableData, TableRow, TreeData, TreeNode, TreemapData, TreemapNode,
    UnplacedCard, UnplacedReason, ViewData, WorkloadBucket, WorkloadData, WorkloadUnit,
};

const FILE_HEADER: &str =
    "// This file is generated by `cargo xtask gen-types`. Do not edit by hand.\n\n";

/// The types to export, collected before any file is written.
///
/// Collecting first is what makes the `add::<T>()` calls in [`main`]
/// the single source of truth. Each generated file needs `import type`
/// lines for the other exported types its declaration mentions, and
/// resolving those against the already-collected set means there is no
/// second hand-maintained list of names to drift out of sync with the
/// calls.
#[derive(Default)]
struct Exports {
    types: Vec<ExportedType>,
}

/// One exported type: the TypeScript name it lands under, and the
/// declaration ts-rs produced for it.
struct ExportedType {
    name: String,
    declaration: String,
}

impl Exports {
    /// Queue `T` for export. Order is preserved but irrelevant —
    /// imports are resolved against the whole set once collection is
    /// finished.
    fn add<T: TS>(&mut self) {
        self.types.push(ExportedType {
            name: T::name(),
            declaration: T::decl(),
        });
    }

    /// Write one `<name>.ts` per collected type into `dir`.
    fn write_all(&self, dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
        for exported in &self.types {
            let path = dir.join(format!("{}.ts", exported.name));

            let mut imports = String::new();
            for dependency in &self.types {
                if dependency.name == exported.name {
                    continue;
                }
                if decl_contains_identifier(&exported.declaration, &dependency.name) {
                    let name = &dependency.name;
                    imports.push_str(&format!("import type {{ {name} }} from './{name}';\n"));
                }
            }
            if !imports.is_empty() {
                imports.push('\n');
            }

            let content = format!("{FILE_HEADER}{imports}export {}\n", exported.declaration);

            std::fs::write(&path, &content)
                .map_err(|error| format!("write {}: {error}", path.display()))?;

            eprintln!("gen-types: wrote {}", path.display());
        }
        Ok(())
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let target_dir = std::path::PathBuf::from(manifest_dir).join("../../ui/src/lib/api/generated");

    std::fs::create_dir_all(&target_dir)
        .map_err(|error| format!("create_dir_all({}): {error}", target_dir.display()))?;

    let mut exports = Exports::default();

    // Diagnostic chain.
    exports.add::<Severity>();
    exports.add::<Diagnostic>();
    exports.add::<DiagnosticBody>();
    exports.add::<FileDiagnostic>();
    exports.add::<FileDiagnosticKind>();
    exports.add::<ItemDiagnostic>();
    exports.add::<ItemDiagnosticKind>();
    exports.add::<FilesDiagnostic>();
    exports.add::<FilesDiagnosticKind>();
    exports.add::<CollectionDiagnostic>();
    exports.add::<CollectionDiagnosticKind>();
    exports.add::<ConfigDiagnostic>();
    exports.add::<ConfigDiagnosticKind>();
    exports.add::<FieldValueError>();
    exports.add::<RangeBound>();

    // Core model wire types.
    exports.add::<WorkItemId>();
    exports.add::<FieldValue>();
    exports.add::<FieldType>();
    exports.add::<ViewType>();
    exports.add::<ViewSummary>();
    exports.add::<DisplayConfig>();
    exports.add::<Aggregate>();
    exports.add::<Bucket>();

    // Editing vocabulary (GET /api/schema).
    exports.add::<SchemaData>();
    exports.add::<FieldSchema>();
    exports.add::<ResourceList>();
    exports.add::<ResourceOption>();
    exports.add::<PaletteColor>();
    exports.add::<FieldTypeOperators>();
    exports.add::<Operator>();
    exports.add::<Condition>();
    exports.add::<Clause>();

    // Mutation contracts (POST /api/items/:id/fields/:field, POST /api/items).
    exports.add::<FieldMutation>();
    exports.add::<FieldMutationResult>();
    exports.add::<CreateItem>();
    exports.add::<CreateItemResult>();

    // View-write contracts (POST /api/views, PATCH /api/views/:id).
    exports.add::<CreateView>();
    exports.add::<SetViewFilter>();
    exports.add::<UpdateView>();
    exports.add::<ViewDefinition>();
    exports.add::<ViewMutationResult>();

    // Timer contracts (GET /api/timer, POST /api/timer/start, POST /api/timer/stop).
    exports.add::<EffortFieldState>();
    exports.add::<TimerMode>();
    exports.add::<TimerPhase>();
    exports.add::<TimerState>();
    exports.add::<StartTimer>();
    exports.add::<TimerStartOutcome>();
    exports.add::<TimerStopResult>();
    exports.add::<TimerWrite>();

    // Git sync contracts (GET /api/git, POST /api/git/pull, POST /api/git/push).
    exports.add::<GitStatus>();
    exports.add::<GitPullResult>();

    // Project identity (GET /api/project).
    exports.add::<ProjectIdentity>();

    // Single-item read projection (GET /api/items/:id).
    exports.add::<ItemDetail>();

    // ViewData enum and common building blocks.
    exports.add::<ViewData>();
    exports.add::<Card>();
    exports.add::<CardField>();
    exports.add::<UnplacedCard>();
    exports.add::<UnplacedReason>();
    exports.add::<ChartValue>();
    exports.add::<SizeValue>();

    // Per-view-kind data.
    exports.add::<BoardData>();
    exports.add::<BoardColumn>();
    exports.add::<Column>();
    exports.add::<TableData>();
    exports.add::<TableRow>();
    exports.add::<ItemRef>();
    exports.add::<TreeData>();
    exports.add::<TreeNode>();
    exports.add::<GraphData>();
    exports.add::<Edge>();
    exports.add::<GanttData>();
    exports.add::<GanttBar>();
    exports.add::<GanttByDepthData>();
    exports.add::<Level>();
    exports.add::<GanttByInitiativeData>();
    exports.add::<Initiative>();
    exports.add::<HeatmapData>();
    exports.add::<HeatmapCell>();
    exports.add::<TreemapData>();
    exports.add::<TreemapNode>();
    exports.add::<LineChartData>();
    exports.add::<LineSeries>();
    exports.add::<LinePoint>();
    exports.add::<BarChartData>();
    exports.add::<BarChartBar>();
    exports.add::<MetricData>();
    exports.add::<MetricRowData>();
    exports.add::<WorkloadData>();
    exports.add::<WorkloadBucket>();
    exports.add::<WorkloadUnit>();

    exports.write_all(&target_dir)?;
    write_view_slot_types(&target_dir)
}

/// The imports and doc comment above the generated slot table.
const SLOT_TABLE_HEADER: &str = r#"import type { FieldType } from './FieldType';
import type { ViewType } from './ViewType';

/**
 * The field types each view kind's structural slots accept, keyed by the
 * slot name used in `views.yaml`. An empty list means any field.
 *
 * Generated from `crates/core/src/model/view_slots.rs`, which is the same
 * table `views_check` validates a saved view against — so the fields the
 * create form offers are the fields the CLI accepts. A view kind with no
 * structural slots (`table`) has an empty entry.
 *
 * A slot's rule can be narrower than its type list: a gantt's input modes
 * are mutually exclusive, and an aggregate's `value` set depends on the
 * function chosen. Those are cross-slot rules, checked on save.
 */
export const VIEW_SLOT_TYPES = {
"#;

/// Closes the generated table. The `satisfies` clause makes a missing view
/// kind a TypeScript error, and `as const` keeps the slot keys literal, so
/// a form control naming a slot the table lacks fails `npm run check`.
const SLOT_TABLE_FOOTER: &str =
    "} as const satisfies Record<ViewType, Readonly<Record<string, readonly FieldType[]>>>;\n";

/// Emit the view-slot type table as a TypeScript constant.
///
/// Not a ts-rs export: this is *data*, not a type. The web UI's view create
/// form needs to know which fields each slot accepts, and
/// `crates/core/src/model/view_slots.rs` is where that is written — so it is
/// generated here rather than hand-maintained beside the form, where it
/// used to drift (two slots were quietly narrower than the CLI's rule).
fn write_view_slot_types(dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut entries = String::new();
    for (kind_index, &kind) in ViewType::VARIANTS.iter().enumerate() {
        let slots = view_slots::slots_of(kind);
        let kind_comma = separator(kind_index, ViewType::VARIANTS.len());
        if slots.is_empty() {
            entries.push_str(&format!("\t{kind}: {{}}{kind_comma}\n"));
            continue;
        }
        entries.push_str(&format!("\t{kind}: {{\n"));
        for (slot_index, slot) in slots.iter().enumerate() {
            let accepts: Vec<String> = slot
                .accepts
                .iter()
                .map(|field_type| format!("'{field_type}'"))
                .collect();
            entries.push_str(&format!(
                "\t\t{}: [{}]{}\n",
                slot.name,
                accepts.join(", "),
                separator(slot_index, slots.len())
            ));
        }
        entries.push_str(&format!("\t}}{kind_comma}\n"));
    }

    let content = format!("{FILE_HEADER}{SLOT_TABLE_HEADER}{entries}{SLOT_TABLE_FOOTER}");
    let path = dir.join("viewSlotTypes.ts");
    std::fs::write(&path, &content)
        .map_err(|error| format!("write {}: {error}", path.display()))?;
    eprintln!("gen-types: wrote {}", path.display());
    Ok(())
}

/// The comma after an object entry — absent on the last one.
fn separator(index: usize, total: usize) -> &'static str {
    if index + 1 == total {
        ""
    } else {
        ","
    }
}

/// Whether `needle` appears in `haystack` as a whole identifier
/// (i.e. not surrounded by other ident characters). Catches `WorkItemId`
/// inside `Array<WorkItemId>` but not inside `FooWorkItemIdBar`.
fn decl_contains_identifier(haystack: &str, needle: &str) -> bool {
    let bytes = haystack.as_bytes();
    let target = needle.as_bytes();
    if target.is_empty() || target.len() > bytes.len() {
        return false;
    }
    for index in 0..=bytes.len() - target.len() {
        if bytes[index..index + target.len()] != *target {
            continue;
        }
        let before_ok = index == 0 || !is_ident_continue(bytes[index - 1]);
        let after_ok =
            index + target.len() == bytes.len() || !is_ident_continue(bytes[index + target.len()]);
        if before_ok && after_ok {
            return true;
        }
    }
    false
}

fn is_ident_continue(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}
