//! Emit TypeScript type bindings for the wire-level Rust types.
//!
//! Invoked indirectly via `cargo xtask gen-types`. ts-rs is the source
//! of truth for the *content* of the generated types (via the `TS`
//! derive on each wire type), but we drive the file writes ourselves
//! rather than calling `T::export_all()`. ts-rs's built-in export path
//! does an atomic temp-file-plus-rename dance that fails with
//! PermissionDenied on WSL2 + Docker Desktop bind mounts; a plain
//! `std::fs::write` works fine. This shim keeps the build path
//! portable across host platforms.
//!
//! When the first endpoint lands, add its wire types to the export
//! list. Each `write_type::<T>(...)` call emits `<T-name>.ts` in the
//! generated dir. Transitive dependencies need their own line — ts-rs
//! doesn't surface them when we drive the writes ourselves.

use std::path::Path;

use ts_rs::TS;

use workdown_core::model::schema::Severity;

const FILE_HEADER: &str =
    "// This file is generated by `cargo xtask gen-types`. Do not edit by hand.\n\n";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let target_dir = std::path::PathBuf::from(manifest_dir).join("../../ui/src/lib/api/generated");

    std::fs::create_dir_all(&target_dir)
        .map_err(|error| format!("create_dir_all({}): {error}", target_dir.display()))?;

    write_type::<Severity>(&target_dir)?;

    Ok(())
}

fn write_type<T: TS>(dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let name = T::name();
    let decl = T::decl();
    let path = dir.join(format!("{name}.ts"));
    let content = format!("{FILE_HEADER}export {decl}\n");

    std::fs::write(&path, &content)
        .map_err(|error| format!("write {}: {error}", path.display()))?;

    eprintln!("gen-types: wrote {}", path.display());
    Ok(())
}
