//! Emit TypeScript type bindings for the wire-level Rust types.
//!
//! Invoked indirectly via `cargo xtask gen-types`. ts-rs is the source
//! of truth for the *content* of the generated types (via the `TS`
//! derive on each wire type), but we drive the file writes ourselves
//! rather than calling `T::export_all()`. ts-rs's built-in export path
//! does an atomic temp-file-plus-rename dance that fails with
//! PermissionDenied on WSL2 + Docker Desktop bind mounts; a plain
//! `std::fs::write` works fine. This shim keeps the build path
//! portable across host platforms.
//!
//! When a new endpoint lands, add its wire types here. Each
//! `write_type::<T>(...)` call emits `<T-name>.ts` in the generated
//! dir. Transitive dependencies need their own line — ts-rs doesn't
//! surface them when we drive the writes ourselves.

use std::path::Path;

use ts_rs::TS;

use workdown_core::item_data::ItemDetail;
use workdown_core::model::diagnostic::{
    CollectionDiagnostic, CollectionDiagnosticKind, ConfigDiagnostic, ConfigDiagnosticKind,
    Diagnostic, DiagnosticBody, FieldValueError, FileDiagnostic, FileDiagnosticKind,
    FilesDiagnostic, FilesDiagnosticKind, ItemDiagnostic, ItemDiagnosticKind,
};
use workdown_core::model::field_value::FieldValue;
use workdown_core::model::schema::{FieldType, Severity};
use workdown_core::model::views::{Aggregate, Bucket, ViewSummary, ViewType};
use workdown_core::model::WorkItemId;
use workdown_core::mutation_data::{
    CreateItem, CreateItemResult, FieldMutation, FieldMutationResult,
};
use workdown_core::schema_data::{FieldSchema, SchemaData};
use workdown_core::view_data::{
    AggregateValue, AxisValue, BarChartBar, BarChartData, BoardColumn, BoardData, Card, CardField,
    Column, Edge, GanttBar, GanttByDepthData, GanttByInitiativeData, GanttData, GraphData,
    HeatmapCell, HeatmapData, Initiative, ItemRef, Level, LineChartData, LinePoint, MetricData,
    MetricRowData, SizeValue, TableData, TableRow, TreeData, TreeNode, TreemapData, TreemapNode,
    UnplacedCard, UnplacedReason, ViewData, WorkloadBucket, WorkloadData, WorkloadUnit,
};

const FILE_HEADER: &str =
    "// This file is generated by `cargo xtask gen-types`. Do not edit by hand.\n\n";

/// Every type name we export. The `write_type` helper scans each
/// declaration for these names (as whole identifiers) and emits an
/// `import type` line for each one referenced. Keep this in sync with
/// the `write_type::<…>` calls in `main` — a name in the list with no
/// matching `write_type` call would generate a broken import; a
/// `write_type` call without a name in the list would skip dependency
/// imports.
const ALL_TYPES: &[&str] = &[
    "Severity",
    "Diagnostic",
    "DiagnosticBody",
    "FileDiagnostic",
    "FileDiagnosticKind",
    "ItemDiagnostic",
    "ItemDiagnosticKind",
    "FilesDiagnostic",
    "FilesDiagnosticKind",
    "CollectionDiagnostic",
    "CollectionDiagnosticKind",
    "ConfigDiagnostic",
    "ConfigDiagnosticKind",
    "FieldValueError",
    "WorkItemId",
    "FieldValue",
    "FieldType",
    "ViewType",
    "ViewSummary",
    "Aggregate",
    "Bucket",
    "SchemaData",
    "FieldSchema",
    "FieldMutation",
    "FieldMutationResult",
    "CreateItem",
    "CreateItemResult",
    "ItemDetail",
    "ViewData",
    "Card",
    "CardField",
    "UnplacedCard",
    "UnplacedReason",
    "AggregateValue",
    "AxisValue",
    "SizeValue",
    "BoardData",
    "BoardColumn",
    "Column",
    "TableData",
    "TableRow",
    "ItemRef",
    "TreeData",
    "TreeNode",
    "GraphData",
    "Edge",
    "GanttData",
    "GanttBar",
    "GanttByDepthData",
    "Level",
    "GanttByInitiativeData",
    "Initiative",
    "HeatmapData",
    "HeatmapCell",
    "TreemapData",
    "TreemapNode",
    "LineChartData",
    "LinePoint",
    "BarChartData",
    "BarChartBar",
    "MetricData",
    "MetricRowData",
    "WorkloadData",
    "WorkloadBucket",
    "WorkloadUnit",
];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let target_dir = std::path::PathBuf::from(manifest_dir).join("../../ui/src/lib/api/generated");

    std::fs::create_dir_all(&target_dir)
        .map_err(|error| format!("create_dir_all({}): {error}", target_dir.display()))?;

    // Diagnostic chain.
    write_type::<Severity>(&target_dir)?;
    write_type::<Diagnostic>(&target_dir)?;
    write_type::<DiagnosticBody>(&target_dir)?;
    write_type::<FileDiagnostic>(&target_dir)?;
    write_type::<FileDiagnosticKind>(&target_dir)?;
    write_type::<ItemDiagnostic>(&target_dir)?;
    write_type::<ItemDiagnosticKind>(&target_dir)?;
    write_type::<FilesDiagnostic>(&target_dir)?;
    write_type::<FilesDiagnosticKind>(&target_dir)?;
    write_type::<CollectionDiagnostic>(&target_dir)?;
    write_type::<CollectionDiagnosticKind>(&target_dir)?;
    write_type::<ConfigDiagnostic>(&target_dir)?;
    write_type::<ConfigDiagnosticKind>(&target_dir)?;
    write_type::<FieldValueError>(&target_dir)?;

    // Core model wire types.
    write_type::<WorkItemId>(&target_dir)?;
    write_type::<FieldValue>(&target_dir)?;
    write_type::<FieldType>(&target_dir)?;
    write_type::<ViewType>(&target_dir)?;
    write_type::<ViewSummary>(&target_dir)?;
    write_type::<Aggregate>(&target_dir)?;
    write_type::<Bucket>(&target_dir)?;

    // Editing vocabulary (GET /api/schema).
    write_type::<SchemaData>(&target_dir)?;
    write_type::<FieldSchema>(&target_dir)?;

    // Mutation contracts (POST /api/items/:id/fields/:field, POST /api/items).
    write_type::<FieldMutation>(&target_dir)?;
    write_type::<FieldMutationResult>(&target_dir)?;
    write_type::<CreateItem>(&target_dir)?;
    write_type::<CreateItemResult>(&target_dir)?;

    // Single-item read projection (GET /api/items/:id).
    write_type::<ItemDetail>(&target_dir)?;

    // ViewData enum and common building blocks.
    write_type::<ViewData>(&target_dir)?;
    write_type::<Card>(&target_dir)?;
    write_type::<CardField>(&target_dir)?;
    write_type::<UnplacedCard>(&target_dir)?;
    write_type::<UnplacedReason>(&target_dir)?;
    write_type::<AggregateValue>(&target_dir)?;
    write_type::<AxisValue>(&target_dir)?;
    write_type::<SizeValue>(&target_dir)?;

    // Per-view-kind data.
    write_type::<BoardData>(&target_dir)?;
    write_type::<BoardColumn>(&target_dir)?;
    write_type::<Column>(&target_dir)?;
    write_type::<TableData>(&target_dir)?;
    write_type::<TableRow>(&target_dir)?;
    write_type::<ItemRef>(&target_dir)?;
    write_type::<TreeData>(&target_dir)?;
    write_type::<TreeNode>(&target_dir)?;
    write_type::<GraphData>(&target_dir)?;
    write_type::<Edge>(&target_dir)?;
    write_type::<GanttData>(&target_dir)?;
    write_type::<GanttBar>(&target_dir)?;
    write_type::<GanttByDepthData>(&target_dir)?;
    write_type::<Level>(&target_dir)?;
    write_type::<GanttByInitiativeData>(&target_dir)?;
    write_type::<Initiative>(&target_dir)?;
    write_type::<HeatmapData>(&target_dir)?;
    write_type::<HeatmapCell>(&target_dir)?;
    write_type::<TreemapData>(&target_dir)?;
    write_type::<TreemapNode>(&target_dir)?;
    write_type::<LineChartData>(&target_dir)?;
    write_type::<LinePoint>(&target_dir)?;
    write_type::<BarChartData>(&target_dir)?;
    write_type::<BarChartBar>(&target_dir)?;
    write_type::<MetricData>(&target_dir)?;
    write_type::<MetricRowData>(&target_dir)?;
    write_type::<WorkloadData>(&target_dir)?;
    write_type::<WorkloadBucket>(&target_dir)?;
    write_type::<WorkloadUnit>(&target_dir)?;

    Ok(())
}

fn write_type<T: TS>(dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let name = T::name();
    let decl = T::decl();
    let path = dir.join(format!("{name}.ts"));

    let mut imports = String::new();
    for dependency in ALL_TYPES {
        if *dependency == name {
            continue;
        }
        if decl_contains_identifier(&decl, dependency) {
            imports.push_str(&format!(
                "import type {{ {dependency} }} from './{dependency}';\n"
            ));
        }
    }
    if !imports.is_empty() {
        imports.push('\n');
    }

    let content = format!("{FILE_HEADER}{imports}export {decl}\n");

    std::fs::write(&path, &content)
        .map_err(|error| format!("write {}: {error}", path.display()))?;

    eprintln!("gen-types: wrote {}", path.display());
    Ok(())
}

/// Whether `needle` appears in `haystack` as a whole identifier
/// (i.e. not surrounded by other ident characters). Catches `WorkItemId`
/// inside `Array<WorkItemId>` but not inside `FooWorkItemIdBar`.
fn decl_contains_identifier(haystack: &str, needle: &str) -> bool {
    let bytes = haystack.as_bytes();
    let target = needle.as_bytes();
    if target.is_empty() || target.len() > bytes.len() {
        return false;
    }
    for index in 0..=bytes.len() - target.len() {
        if bytes[index..index + target.len()] != *target {
            continue;
        }
        let before_ok = index == 0 || !is_ident_continue(bytes[index - 1]);
        let after_ok =
            index + target.len() == bytes.len() || !is_ident_continue(bytes[index + target.len()]);
        if before_ok && after_ok {
            return true;
        }
    }
    false
}

fn is_ident_continue(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}
